DROP TABLE IF EXISTS users;

CREATE TABLE users(
 login VARCHAR(70) NOT NULL PRIMARY KEY,
 password VARCHAR(100) NOT NULL);

INSERT INTO users VALUES('user', '$2a$10$MnJJd7eoq62gH5BZRxgYpuBXbOy5U.iGo1Jc3JeIJ8IQ4qx5egrW.');