DROP TABLE IF EXISTS users;

CREATE TABLE users(
 login VARCHAR(70) NOT NULL PRIMARY KEY,
 password VARCHAR(100) NOT NULL);

INSERT INTO users VALUES('user', '$2a$10$.iTaoR0c1G0XUTpQUClB..oGzDQQfTUWL6NLWA3wU8IdEJIFF9FHG');